language: node_js
node_js:
  - 10
  - 12
cache:
  directories:
  - node_modules
before_install:
  # Create a master branch for commitlint
  # https://github.com/conventional-changelog/commitlint/issues/6
  - git remote set-branches origin master && git fetch
before_deploy:
  echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
jobs:
  include:
    # Define the release stage that publishes lerna to npm
    - stage: release
      deploy:
          on:
            branch: master
          provider: script
          skip_cleanup: true
          script:
            - npm run lerna:deploy -- "${TRAVIS_COMMIT_MESSAGE}"
