name: Manually Publish

on: workflow_dispatch
jobs:
  info:
    name: Check commit
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - id: commit
      run: echo "::set-output name=message::${{ github.event.head_commit.message }}"
    outputs:
      commitMsg: ${{ steps.commit.outputs.message }}
  publish:
    name: Publish
    needs: [info]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: main
      - name: Node Install
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Installing Packages
        env:
          NODE_ENV: development
        run: npm ci
      - name: Testing Packages
        run: npm test
      - name: Releasing Packages
        env:
          NODE_ENV: production
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
        run: |-
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
          npm run lerna:publish