name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.x', '18.x' ]
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git remote set-branches --add origin main
          git fetch
      - name: Node Install
        with:
          node-version: ${{ matrix.node }}
        uses: actions/setup-node@v1
      - name: Installing Packages
        env:
          NODE_ENV: development
        run: npm ci
      - name: Unit Tests
        run: npm run test
